server:
  port: 9000

spring:
  application:
    name: api-gateway
  boot:
    admin:
      client:
        url: http://192.168.99.1:8000 #springboot admin管理中心地址
        instance:
          service-base-url: http://192.168.99.1:9000 #让springboot admin管理中心发现本服务

#将访问路径映射到对应的服务
zuul:
  routes:
    eureka-service-a:
      path: /service-a/**
    eureka-service-b:
      path: /service-b/**
    eureka-service-c:
      path: /service-c/**
  prefix: /api #路径访问前缀

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://192.168.99.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理